services:
  valharvest-food:
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: always
    ports:
      - "3035:3035"
    extra_hosts:
      - "host.docker.internal:host-gateway"
