name: Node.js CI

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: self-hosted
    strategy:
      matrix:
        node: [ 16 ]
    steps:
    - uses: actions/checkout@v3
    - name: Create env file
      run: |
        touch .env
        echo MYSQL_HOST=${{ secrets.MYSQL_HOST }} >> .env
        echo MYSQL_USER=${{ secrets.MYSQL_USER }} >> .env
        echo MYSQL_PASS=${{ secrets.MYSQL_PASS }} >> .env
        echo MYSQL_NAME=${{ secrets.MYSQL_NAME }} >> .env
        echo SECRET=${{ secrets.API_SECRET }} >> .env
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: docker-compose up -d --build
